namespace HextechRunes;

internal static partial class HextechContentRegistry
{
    private static readonly IReadOnlyList<RuneRegistration> RuneRegistrations =
    [
        Rune<SlapRune>(HextechRarityTier.Silver),
        Rune<DexterityToStrengthRune>(HextechRarityTier.Silver, flags: RuneFlags.AttributeConversionExclusive),
        Rune<StrengthToDexterityRune>(HextechRarityTier.Silver, flags: RuneFlags.AttributeConversionExclusive),
        Rune<DexterityStrengthToFocusRune>(HextechRarityTier.Silver, flags: RuneFlags.AttributeConversionExclusive, characterPool: HextechCharacterPool.Defect, characterOrder: 1),
        Rune<WizardlyThinkingRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Defect, characterOrder: 2),
        Rune<NimbleRune>(HextechRarityTier.Silver),
        Rune<EscapePlanRune>(HextechRarityTier.Silver, flags: RuneFlags.Disabled),
        Rune<BadTasteRune>(HextechRarityTier.Silver),
        Rune<FirstAidKitRune>(HextechRarityTier.Silver),
        Rune<RegenerationSuppressionRune>(HextechRarityTier.Silver),
        Rune<GiantSerpentsFangRune>(HextechRarityTier.Silver),
        Rune<SpeedDemonRune>(HextechRarityTier.Silver),
        Rune<HeavyHitterRune>(HextechRarityTier.Silver),
        Rune<BigStrengthRune>(HextechRarityTier.Silver),
        Rune<TormentorRune>(HextechRarityTier.Silver),
        Rune<AdamantRune>(HextechRarityTier.Silver),
        Rune<MountainSoulRune>(HextechRarityTier.Silver),
        Rune<FrostWraithRune>(HextechRarityTier.Silver),
        Rune<BadgeBrothersRune>(HextechRarityTier.Silver),
        Rune<HomeguardRune>(HextechRarityTier.Silver),
        Rune<SwiftAndSafeRune>(HextechRarityTier.Silver),
        Rune<SacrificeRune>(HextechRarityTier.Silver),
        Rune<ProtectiveVeilRune>(HextechRarityTier.Silver),
        Rune<RepulsorRune>(HextechRarityTier.Silver),
        Rune<LightEmUpRune>(HextechRarityTier.Silver),
        Rune<UltimateUnstoppableRune>(HextechRarityTier.Silver),
        Rune<ThornmailRune>(HextechRarityTier.Silver),
        Rune<ZealotRune>(HextechRarityTier.Silver),
        Rune<MindToMatterRune>(HextechRarityTier.Silver),
        Rune<StatsRune>(HextechRarityTier.Silver),
        Rune<StartupRoutineRune>(HextechRarityTier.Silver),
        Rune<CollectorRune>(HextechRarityTier.Silver),
        Rune<UnyieldingArmorRune>(HextechRarityTier.Silver, flags: RuneFlags.Disabled),
        Rune<NightParadeRune>(HextechRarityTier.Silver),
        Rune<BloodPactRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Ironclad, characterOrder: 2),
        Rune<PlateletRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Ironclad, characterOrder: 3),
        Rune<SnakebiteRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Silent, characterOrder: 7),
        Rune<CatalystRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Silent, characterOrder: 10),
        Rune<SwordIntentRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Regent, characterOrder: 3),
        Rune<FlawlessRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Regent, characterOrder: 4),
        Rune<CondensedRadianceRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Regent, characterOrder: 5),
        Rune<RoyalCommandRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Regent, characterOrder: 10),
        Rune<ByproductRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Defect, characterOrder: 7),
        Rune<ElectricSurgeRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Defect, characterOrder: 9),
        Rune<SoulCallingRune>(HextechRarityTier.Silver),
        Rune<TauntRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 5),
        Rune<SwordsmanshipRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Regent, characterOrder: 9),
        Rune<AdvanceToRetreatRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Ironclad, characterOrder: 7),
        Rune<BoneGuardRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 12),
        Rune<PlasterRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 13),
        Rune<EasyDoesItRune>(HextechRarityTier.Silver),
        Rune<SweepingBladeRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Ironclad, characterOrder: 14),
        Rune<OceanDragonSoulRune>(HextechRarityTier.Silver),
        Rune<InfernalDragonSoulRune>(HextechRarityTier.Silver),
        Rune<HextechDragonSoulRune>(HextechRarityTier.Silver),
        Rune<CarefulSelectionRune>(HextechRarityTier.Silver),
        Rune<PowerShieldRune>(HextechRarityTier.Silver),
        Rune<CorrosionRune>(HextechRarityTier.Silver),
        Rune<DizzySpinningRune>(HextechRarityTier.Silver),
        Rune<WarmupExerciseRune>(HextechRarityTier.Silver),
        Rune<BerserkRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Ironclad, characterOrder: 11),
        Rune<BrutalityRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Ironclad, characterOrder: 12),
        Rune<CurtainCallRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Silent, characterOrder: 11),
        Rune<AllInRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Silent, characterOrder: 14),
        Rune<InstantDeathRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 18),
        Rune<BarbarianWayRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Defect, characterOrder: 13),
        Rune<GloomyCloudsRune>(HextechRarityTier.Silver, characterPool: HextechCharacterPool.Defect, characterOrder: 14),
        Rune<MentalShieldRune>(HextechRarityTier.Silver),
        Rune<PacifistRune>(HextechRarityTier.Silver),
        Rune<CrackTheEggRune>(HextechRarityTier.Silver),
        Rune<KakaRune>(HextechRarityTier.Silver),
        Rune<BrutalForceRune>(HextechRarityTier.Silver),
        Rune<TransmuteGoldRune>(HextechRarityTier.Silver),

        Rune<JudicatorRune>(HextechRarityTier.Gold),
        Rune<TranscendentEvilRune>(HextechRarityTier.Gold, flags: RuneFlags.ThirdActExcluded, characterPool: HextechCharacterPool.Defect, characterOrder: 3),
        Rune<TankEngineRune>(HextechRarityTier.Gold, flags: RuneFlags.ThirdActExcluded),
        Rune<AstralBodyRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<AncientWineRune>(HextechRarityTier.Gold),
        Rune<HolyFireRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<NoNonsenseRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<SuperBrainRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<OverflowRune>(HextechRarityTier.Gold),
        Rune<SturdyRune>(HextechRarityTier.Gold),
        Rune<LoopRune>(HextechRarityTier.Gold),
        Rune<OkBoomerangRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<DivineInterventionRune>(HextechRarityTier.Gold),
        Rune<SonataRune>(HextechRarityTier.Gold),
        Rune<CuttingEdgeAlchemistRune>(HextechRarityTier.Gold),
        Rune<DevilsDanceRune>(HextechRarityTier.Gold),
        Rune<BeginningAndEndRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 3),
        Rune<KeystoneHunterRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Silent, characterOrder: 1),
        Rune<WarmogsSpiritRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<RedEnvelopeRune>(HextechRarityTier.Gold),
        Rune<MindPurificationRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<EndlessRecoveryRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<SpeedsterRune>(HextechRarityTier.Gold),
        Rune<ServantMasterRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 1),
        Rune<SoulEaterRune>(HextechRarityTier.Gold),
        Rune<DonationRune>(HextechRarityTier.Gold),
        Rune<TwiceThriceRune>(HextechRarityTier.Gold),
        Rune<BreadAndButterRune>(HextechRarityTier.Gold),
        Rune<BreadAndCheeseRune>(HextechRarityTier.Gold),
        Rune<BreadAndJamRune>(HextechRarityTier.Gold),
        Rune<FirebrandRune>(HextechRarityTier.Gold),
        Rune<NightstalkingRune>(HextechRarityTier.Gold),
        Rune<GetExcitedRune>(HextechRarityTier.Gold),
        Rune<ShrinkEngineRune>(HextechRarityTier.Gold, flags: RuneFlags.ThirdActExcluded),
        Rune<StatsOnStatsRune>(HextechRarityTier.Gold),
        Rune<LifeFlowRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Ironclad, characterOrder: 1),
        Rune<RekindleRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Ironclad, characterOrder: 4),
        Rune<TrickLicenseRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Silent, characterOrder: 2),
        Rune<GalacticGiftRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Regent, characterOrder: 1),
        Rune<SomethingFromNothingRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 2),
        Rune<LubricantRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Defect, characterOrder: 4),
        Rune<HubrisRune>(HextechRarityTier.Gold, flags: RuneFlags.ThirdActExcluded),
        Rune<DrainRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 4),
        Rune<LethalTempoRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Silent, characterOrder: 3),
        Rune<EmergenceRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Defect, characterOrder: 5),
        Rune<MirageRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Silent, characterOrder: 5),
        Rune<AdaptiveCapacitorRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Defect, characterOrder: 8),
        Rune<RenewalRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Silent, characterOrder: 4),
        Rune<WraithRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 6),
        Rune<SummonForthRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Regent, characterOrder: 2),
        Rune<ImmortalBoneRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 7),
        Rune<MakeItMineRune>(HextechRarityTier.Gold, flags: RuneFlags.ThirdActExcluded, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 8),
        Rune<DoomsdayRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 14),
        Rune<OldIdolRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<MonarchsGazeRune>(HextechRarityTier.Gold),
        Rune<HardBonesRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 11),
        Rune<SendThemInRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Regent, characterOrder: 8),
        Rune<ChainInSleeveRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Silent, characterOrder: 9),
        Rune<RoyalTrialRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Regent, characterOrder: 11),
        Rune<GoodLuckRune>(HextechRarityTier.Gold),
        Rune<RadianceRune>(HextechRarityTier.Gold),
        Rune<ManipulateRealityRune>(HextechRarityTier.Gold),
        Rune<BlueCandleMedkitRune>(HextechRarityTier.Gold),
        Rune<BigHandsRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 15),
        Rune<JinlianBoxRune>(HextechRarityTier.Gold, flags: RuneFlags.ThirdActExcluded),
        Rune<FleshAndBoneRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 16),
        Rune<PortableSleepingBagRune>(HextechRarityTier.Gold),
        Rune<MoreTheMerrierRune>(HextechRarityTier.Gold),
        Rune<MirrorReflectionRune>(HextechRarityTier.Gold, flags: RuneFlags.FirstActExcluded),
        Rune<BloodArmorRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Ironclad, characterOrder: 9),
        Rune<ScaredStiffRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Ironclad, characterOrder: 10),
        Rune<DeviantCognitionRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Ironclad, characterOrder: 13),
        Rune<CorpseExplosionRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Silent, characterOrder: 12),
        Rune<SwordFlightRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled, characterPool: HextechCharacterPool.Regent, characterOrder: 13),
        Rune<ElectrodynamicsRune>(HextechRarityTier.Gold, characterPool: HextechCharacterPool.Defect, characterOrder: 15),
        Rune<EnlightenmentRune>(HextechRarityTier.Gold),
        Rune<WhiteHoleRune>(HextechRarityTier.Gold),
        Rune<TanksShieldRune>(HextechRarityTier.Gold),
        Rune<TransmutePrismaticRune>(HextechRarityTier.Gold),
        Rune<DawnbringersResolveRune>(HextechRarityTier.Gold, flags: RuneFlags.Disabled),
        Rune<ShrinkRayRune>(HextechRarityTier.Gold),

        Rune<EurekaRune>(HextechRarityTier.Prismatic),
        Rune<InfiniteLoopRune>(HextechRarityTier.Prismatic, flags: RuneFlags.ThirdActExcluded),
        Rune<SlowCookRune>(HextechRarityTier.Prismatic),
        Rune<GiantSlayerRune>(HextechRarityTier.Prismatic),
        Rune<CourageOfColossusRune>(HextechRarityTier.Prismatic),
        Rune<GlassCannonRune>(HextechRarityTier.Prismatic),
        Rune<FinalFormRune>(HextechRarityTier.Prismatic),
        Rune<BackToBasicsRune>(HextechRarityTier.Prismatic),
        Rune<DrawYourSwordRune>(HextechRarityTier.Prismatic),
        Rune<FeelTheBurnRune>(HextechRarityTier.Prismatic, flags: RuneFlags.Disabled),
        Rune<MikaelsBlessingRune>(HextechRarityTier.Prismatic, flags: RuneFlags.Disabled),
        Rune<EarthAwakensRune>(HextechRarityTier.Prismatic),
        Rune<SymphonyOfWarRune>(HextechRarityTier.Prismatic),
        Rune<UnmovableMountainRune>(HextechRarityTier.Prismatic),
        Rune<MysteryRune>(HextechRarityTier.Prismatic),
        Rune<MadScientistRune>(HextechRarityTier.Prismatic),
        Rune<JeweledGauntletRune>(HextechRarityTier.Prismatic),
        Rune<HailToTheKingRune>(HextechRarityTier.Prismatic, flags: RuneFlags.ThirdActExcluded),
        Rune<ArcanePunchRune>(HextechRarityTier.Prismatic),
        Rune<PandorasBoxRune>(HextechRarityTier.Prismatic, flags: RuneFlags.FirstActExcluded),
        Rune<TapDanceRune>(HextechRarityTier.Prismatic),
        Rune<InfernalConduitRune>(HextechRarityTier.Prismatic),
        Rune<DualWieldRune>(HextechRarityTier.Prismatic),
        Rune<GoliathRune>(HextechRarityTier.Prismatic),
        Rune<MasterOfDualityRune>(HextechRarityTier.Prismatic),
        Rune<HandOfBaronRune>(HextechRarityTier.Prismatic),
        Rune<CantTouchThisRune>(HextechRarityTier.Prismatic),
        Rune<QueenRune>(HextechRarityTier.Prismatic),
        Rune<UltimateRefreshRune>(HextechRarityTier.Prismatic),
        Rune<GoldrendRune>(HextechRarityTier.Prismatic),
        Rune<CerberusRune>(HextechRarityTier.Prismatic),
        Rune<CircleOfDeathRune>(HextechRarityTier.Prismatic),
        Rune<FanTheHammerRune>(HextechRarityTier.Prismatic),
        Rune<FeyMagicRune>(HextechRarityTier.Prismatic),
        Rune<WatchOutGrapefruitRune>(HextechRarityTier.Prismatic),
        Rune<ProteinShakeRune>(HextechRarityTier.Prismatic),
        Rune<StatsOnStatsOnStatsRune>(HextechRarityTier.Prismatic),
        Rune<GoldenSpatulaRune>(HextechRarityTier.Prismatic, flags: RuneFlags.ThirdActExcluded),
        Rune<PrecisionCognitionRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Defect, characterOrder: 6),
        Rune<HastyScribbleRune>(HextechRarityTier.Prismatic),
        Rune<ClownCollegeRune>(HextechRarityTier.Prismatic),
        Rune<BladeWaltzRune>(HextechRarityTier.Prismatic),
        Rune<SingularityAIRune>(HextechRarityTier.Prismatic),
        Rune<EightPennyGateRune>(HextechRarityTier.Prismatic),
        Rune<MobileHomeRune>(HextechRarityTier.Prismatic),
        Rune<GrowingStrongerRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Ironclad, characterOrder: 5),
        Rune<GroundedRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Ironclad, characterOrder: 6),
        Rune<KillerHunterRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Silent, characterOrder: 6),
        Rune<SerpentsFangRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Silent, characterOrder: 8),
        Rune<ExplosionArtRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Regent, characterOrder: 6),
        Rune<StarlightSplendorRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Regent, characterOrder: 7),
        Rune<MiserableFateRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 9),
        Rune<DieForYouRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 10),
        Rune<HappyAccidentRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Defect, characterOrder: 10),
        Rune<MiseryRune>(HextechRarityTier.Prismatic),
        Rune<GhostFormRune>(HextechRarityTier.Prismatic),
        Rune<ForbiddenGrimoireRune>(HextechRarityTier.Prismatic),
        Rune<OneLaneBridgeRune>(HextechRarityTier.Prismatic, flags: RuneFlags.Disabled),
        Rune<OrbSymbiosisRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Defect, characterOrder: 11),
        Rune<NearDeathFeastRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Ironclad, characterOrder: 8),
        Rune<UnsealedThroneRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Regent, characterOrder: 12),
        Rune<CoreOverloadRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Defect, characterOrder: 12),
        Rune<ForgottenSoulRune>(HextechRarityTier.Prismatic),
        Rune<UpgradeRune>(HextechRarityTier.Prismatic),
        Rune<OmniDragonSoulRune>(HextechRarityTier.Prismatic),
        Rune<ShoulderVakuRune>(HextechRarityTier.Prismatic),
        Rune<PrimitiveMadnessRune>(HextechRarityTier.Prismatic),
        Rune<ThoughtOverwriteRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Necrobinder, characterOrder: 17),
        Rune<DoubleExistenceRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Silent, characterOrder: 13),
        Rune<TriPrismRune>(HextechRarityTier.Prismatic, characterPool: HextechCharacterPool.Regent, characterOrder: 14),
        Rune<QuantumComputingRune>(HextechRarityTier.Prismatic),
        Rune<MindOverMatterRune>(HextechRarityTier.Prismatic),
        Rune<DuffsVintageRune>(HextechRarityTier.Prismatic),
        Rune<TransmuteChaosRune>(HextechRarityTier.Prismatic)
    ];
}
